apiVersion: builtin
kind: SecretGenerator
metadata:
  name: ksops-secret-generator
  annotations:
    config.kubernetes.io/function: |
      container: ghcr.io/viaduct-ai/kustomize-sops:v4.2.1
behavior: create
literals:
  - dummy=dummy
