apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: 1password
  namespace: 1password
spec:
  interval: 5m
  chart:
    spec:
      chart: connect
      sourceRef:
        kind: HelmRepository
        name: 1password
        namespace: 1password
  values:
    connect:
      credentialsExistingSecret: op-credentials
      credentialsExistingSecretKey: 1password-credentials.json
    operator:
      create: true
      token:
        existingSecret: onepassword-token
        existingSecretKey: token
