apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: 1password
  namespace: 1password
spec:
  interval: 5m
  chart:
    spec:
      chart: connect
      sourceRef:
        kind: HelmRepository
        name: 1password
        namespace: 1password
  values:
    connect:
      credentials:
        existingSecret: 1password-credentials #pragma: allowlist secret
    operator:
      create: true
      token:
        existingSecret: 1password-token #pragma: allowlist secret
        existingSecretKey: token #pragma: allowlist secret
