apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-secrets
  namespace: redis
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-vault
  target:
    name: redis-secrets
    creationPolicy: Owner
  data:
    - secretKey: redis-password
      remoteRef:
        key: authentik-secrets/redis_password
