apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  interval: 10m
  url: https://k3rnelpan1c-dev.github.io/uptime-kuma-helm/
