site_name: KJHome Homelab Docs
site_url: https://docs.kjho.me
docs_dir: docs-src
site_dir: docs
repo_url: https://github.com/kylejschultz/kjho.me

nav:
  - Home: index.md
  - Infrastructure:
    - GitOps Workflow: infrastructure/gitops-workflow.md
    - Service Directory: infrastructure/service-directory.md
  - Core:
    - Security:
      - Authentik: core/security/authentik-setup.md
    - Networking:
      - Cloudflare Tunnel: core/networking/cloudflare-tunnel.md
      - External-DNS: core/networking/external-dns.md
    - Storage:
      - Longhorn: core/storage/longhorn.md
    - Database:
      - PostgreSQL: core/database/postgresql.md
      - Redis: core/database/redis.md
    - Observability:
      - Uptime Kuma: core/observability/uptime-kuma.md
  # - Apps:
    # Future non-core applications will go here
  - Troubleshooting: troubleshooting.md

theme:
  name: swan
  # SWAN theme configuration (based on Material for MkDocs)
  logo: https://github.com/kylejschultz/kjho.me/raw/docs/assets/images/logo_transparent.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

plugins:
  - search

extra_css:
  - stylesheets/extra.css

extra:
  generator: false
