site_name: KJHome Homelab Docs
site_url: https://docs.kjho.me
docs_dir: docs-src
site_dir: docs

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Authentication:
    - Authentik Setup: authentication/authentik-setup.md
  - Infrastructure:
    - GitOps Workflow: infrastructure/gitops-workflow.md
    - Service Directory: infrastructure/service-directory.md
  - Troubleshooting: troubleshooting.md

theme:
  name: material
  palette:
    - scheme: slate
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

plugins:
  - search
