apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: ingress-traefik
spec:
  interval: 10m
  chart:
    spec:
      chart: traefik
      version: 36.3.0
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: ingress-traefik
  values:
    deployment:
      enabled: true
    service:
      enabled: true
      type: LoadBalancer
    ingressRoute:
      dashboard:
        enabled: true
    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
      websecure:
        tls:
          enabled: true
    providers:
      kubernetesCRD:
        enabled: true
      kubernetesIngress:
        enabled: true
    ingressClass:
      enabled: true
      isDefaultClass: true
