apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cert-manager.yaml
- cloudflared.yaml
- ddns.yaml
- external-dns.yaml
- longhorn-system.yaml
- postgresql.yaml
- redis.yaml
- traefik.yaml
- uptime-kuma.yaml
