apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  interval: 5m
  chart:
    spec:
      chart: uptime-kuma
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: uptime-kuma
        namespace: uptime-kuma
  values:
    persistence:
      enabled: true
      storageClass: longhorn
      size: 10Gi
      name: uptime-kuma-data
    podSecurityContext:
      fsGroup: 1000
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-cloudflare
      hosts:
        - host: uptime.kjho.me
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - uptime.kjho.me
          secretName: uptime-kuma-tls
