apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-crds
  namespace: flux-system
spec:
  interval: 10m0s
  path: deploy/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: cert-manager
  dependsOn: []
  wait: true
  timeout: 2m0s
  postBuild:
    substitute:
      "{{ template \"cert-manager.name\" . }}": "cert-manager"
      "{{ .Release.Name }}": "cert-manager"
