apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: traefik-crds
  namespace: flux-system
spec:
  interval: 360m
  path: traefik/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: traefik
