apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik
      version: '2025.6.3'  # Latest version
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
      interval: 1m
  values:
    authentik:
      error_reporting:
        enabled: false
      postgresql:
        password:
          existingSecret: authentik-secrets
          key: postgresPassword
        host: authentik-postgresql
      redis:
        host: redis.redis.svc.cluster.local
        password:
          required: false

    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-cloudflare
      hosts:
        - host: auth.kjho.me
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: authentik-tls
          hosts:
            - auth.kjho.me

    postgresql:
      enabled: true
      persistence:
        enabled: true
        storageClass: longhorn
      auth:
        existingSecret: authentik-secrets
        secretKeys:
          adminPasswordKey: postgresPassword
          userPasswordKey: postgresPassword
          replicationPasswordKey: postgresPassword
