apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-vault
  target:
    name: authentik-secrets
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: authentik/postgres-password
    - secretKey: secret_key
      remoteRef:
        key: authentik/secret-key
