apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: authentik-secrets
    template:
      engineVersion: v2
      data:
        # PostgreSQL password used by both authentik and PostgreSQL
        postgresPassword: "{{ .postgresPassword }}"
        # Authentik secret key for encryption
        secretKey: "{{ .secretKey }}"
  data:
    - secretKey: authentik-postgres-password
      remoteRef:
        key: authentik
        property: postgres-password
    - secretKey: authentik-secret-key
      remoteRef:
        key: authentik
        property: secret-key
