apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-ddns
  namespace: ddns
  labels:
    app: cloudflare-ddns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-ddns
  template:
    metadata:
      labels:
        app: cloudflare-ddns
    spec:
      containers:
      - name: cloudflare-ddns
        image: curlimages/curl:latest
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args:
        - -c
        - |
          while true; do
            echo "$(date): Checking current IP..."
            CURRENT_IP=$(curl -s https://ipv4.icanhazip.com)
            echo "$(date): Current IP is $CURRENT_IP"

            # Get zone ID
            ZONE_ID=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones?name=$ZONE" \
              -H "Authorization: Bearer $API_TOKEN" \
              -H "Content-Type: application/json" | \
              sed -n 's/.*"id":"\([^"]*\)".*/\1/p' | head -1)

            # Get record ID and current DNS IP
            RECORD_INFO=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/$ZONE_ID/dns_records?name=$RECORD" \
              -H "Authorization: Bearer $API_TOKEN" \
              -H "Content-Type: application/json")

            RECORD_ID=$(echo "$RECORD_INFO" | sed -n 's/.*"id":"\([^"]*\)".*/\1/p' | head -1)
            DNS_IP=$(echo "$RECORD_INFO" | sed -n 's/.*"content":"\([^"]*\)".*/\1/p' | head -1)

            if [ "$CURRENT_IP" != "$DNS_IP" ]; then
              echo "$(date): IP changed from $DNS_IP to $CURRENT_IP, updating DNS..."
              curl -s -X PUT "https://api.cloudflare.com/client/v4/zones/$ZONE_ID/dns_records/$RECORD_ID" \
                -H "Authorization: Bearer $API_TOKEN" \
                -H "Content-Type: application/json" \
                --data '{"type":"A","name":"'"$RECORD"'","content":"'"$CURRENT_IP"'","ttl":300}'
              echo "$(date): DNS update completed"
            else
              echo "$(date): IP unchanged, no update needed"
            fi

            echo "$(date): Sleeping for 5 minutes..."
            sleep 300
          done
        env:
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-ddns-secret
              key: API_TOKEN
        - name: ZONE
          valueFrom:
            secretKeyRef:
              name: cloudflare-ddns-secret
              key: ZONE
        - name: RECORD
          valueFrom:
            secretKeyRef:
              name: cloudflare-ddns-secret
              key: RECORD
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 100
          runAsGroup: 101
      restartPolicy: Always
