apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-vault
  target:
    name: authentik-secrets
    creationPolicy: Owner
  data:
    - secretKey: secret_key
      remoteRef:
        key: authentik-secrets/secret_key
    - secretKey: redis_password
      remoteRef:
        key: authentik-secrets/redis_password
    - secretKey: postgres_password
      remoteRef:
        key: authentik-secrets/postgres_password
