apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-vault
  target:
    name: authentik-secrets
    creationPolicy: Owner
  data:
    - secretKey: secret_key
      remoteRef:
        key: authentik-secrets/secret_key
