apiVersion: v1
kind: Service
metadata:
  name: authentik-external-dns
  namespace: authentik
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "auth.kjho.me"
    external-dns.alpha.kubernetes.io/target: "4b8b2aac-eb36-4cc9-a664-9db4d6cf3bb0.cfargotunnel.com"
spec:
  type: ExternalName
  externalName: "4b8b2aac-eb36-4cc9-a664-9db4d6cf3bb0.cfargotunnel.com"
