---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik
      version: 2025.4.1
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  values:
    server:
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - host: auth.kjho.me
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: authentik-tls
            hosts:
              - auth.kjho.me
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-cloudflare"
    authentik:
      redis:
        host: redis-master.redis.svc.cluster.local
        port: 6379
    redis:
      enabled: false
    postgresql:
      enabled: true
      auth:
        existingSecret: authentik-secrets
        secretKeys:
          adminPasswordKey: postgres_password
          userPasswordKey: postgres_password
      primary:
        persistence:
          enabled: true
          size: 8Gi
          storageClass: longhorn
  valuesFrom:
    - kind: Secret
      name: authentik-secrets
      valuesKey: secret_key
      targetPath: authentik.secret_key
    - kind: Secret
      name: authentik-secrets
      valuesKey: redis_password
      targetPath: authentik.redis.password
