apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 10m
  timeout: 10m
  install:
    timeout: 10m
    remediation:
      retries: 3
  upgrade:
    timeout: 10m
    remediation:
      retries: 3
      remediateLastFailure: true
  chart:
    spec:
      chart: authentik
      version: '2024.6.3'
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  values:
    global:
      env:
        - name: AUTHENTIK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: authentik-secret
              key: secret_key
        - name: AUTHENTIK_POSTGRESQL__HOST
          value: postgresql.postgresql.svc.cluster.local
        - name: AUTHENTIK_POSTGRESQL__NAME
          value: authentik
        - name: AUTHENTIK_POSTGRESQL__USER
          value: postgres
        - name: AUTHENTIK_POSTGRESQL__PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-secret
              key: postgresql_password
        - name: AUTHENTIK_REDIS__HOST
          value: redis-master.redis.svc.cluster.local
        - name: AUTHENTIK_REDIS__PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-secret
              key: redis_password

    authentik:
      error_reporting:
        enabled: false

    server:
      # No ingress - using Cloudflare tunnel
      ingress:
        enabled: false

    # Use external PostgreSQL instead of bundled one
    postgresql:
      enabled: false
