apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 10m
  timeout: 10m
  install:
    timeout: 10m
    remediation:
      retries: 3
  upgrade:
    timeout: 10m
    remediation:
      retries: 3
      remediateLastFailure: true
  chart:
    spec:
      chart: authentik
      version: '2024.6.3'
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  values:
    authentik:
      error_reporting:
        enabled: false
      postgresql:
        host: postgresql.postgresql.svc.cluster.local
        name: authentik
        user: postgres
        password:
          valueFrom:
            secretKeyRef:
              name: authentik-secret
              key: postgresql_password
      redis:
        host: redis-master.redis.svc.cluster.local
        password:
          valueFrom:
            secretKeyRef:
              name: authentik-secret
              key: redis_password

    server:
      env:
        AUTHENTIK_SECRET_KEY:
          valueFrom:
            secretKeyRef:
              name: authentik-secret
              key: secret_key
      # No ingress - using Cloudflare tunnel
      ingress:
        enabled: false

    worker:
      env:
        AUTHENTIK_SECRET_KEY:
          valueFrom:
            secretKeyRef:
              name: authentik-secret
              key: secret_key

    # Use external PostgreSQL instead of bundled one
    postgresql:
      enabled: false
