apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: discord-webhook-url
  namespace: flux-system
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-vault
  target:
    name: discord-webhook-url
    creationPolicy: Owner
  data:
    - secretKey: address
      remoteRef:
        key: discord-webhook/secret/url
