apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgresql
spec:
  interval: 10m
  chart:
    spec:
      chart: postgresql
      version: "16.6.3"
      sourceRef:
        kind: HelmRepository
        name: postgresql
        namespace: postgresql
  values:
    auth:
      existingSecret: postgresql-secrets
      secretKeys:
        adminPasswordKey: postgres-password
        userPasswordKey: password
    primary:
      persistence:
        enabled: true
        size: 20Gi
        storageClass: longhorn
      resources:
        requests:
          memory: 256Mi
          cpu: 250m
        limits:
          memory: 512Mi
          cpu: 500m
      nodeSelector:
        kubernetes.io/hostname: nuc1
    metrics:
      enabled: true
      serviceMonitor:
        enabled: false
