apiVersion: v1
kind: Service
metadata:
  name: longhorn-external-dns
  namespace: longhorn-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: longhorn.kjho.me
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  type: ExternalName
  externalName: 0a5fdf0e-8949-45ac-86ad-cac3bf8d50ce.cfargotunnel.com
