apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: nucx
  namespace: longhorn-system
spec:
  disks:
    data1:
      path: /mnt/data1/longhorn/
      allowScheduling: true
      evictionRequested: false
      storageReserved: 107374182400  # 100GB reserved
      tags:
        - fast
        - primary
      diskType: filesystem
---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: nuc1
  namespace: longhorn-system
spec:
  disks:
    nvme0:
      path: /var/lib/longhorn/
      allowScheduling: true
      evictionRequested: false
      storageReserved: 53687091200  # 50GB reserved
      tags:
        - fast
        - nvme
      diskType: filesystem
---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: nuc2
  namespace: longhorn-system
spec:
  disks:
    nvme0:
      path: /var/lib/longhorn/
      allowScheduling: true
      evictionRequested: false
      storageReserved: 53687091200  # 50GB reserved
      tags:
        - fast
        - nvme
      diskType: filesystem
---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: nuc3
  namespace: longhorn-system
spec:
  disks:
    nvme0:
      path: /var/lib/longhorn/
      allowScheduling: true
      evictionRequested: false
      storageReserved: 53687091200  # 50GB reserved
      tags:
        - fast
        - nvme
      diskType: filesystem
