apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: ingress-traefik
spec:
  interval: 10m
  chart:
    spec:
      chart: traefik
      version: 36.3.0
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: ingress-traefik
  values:
    deployment:
      enabled: true
    service:
      enabled: true
      type: NodePort
    api:
      dashboard: true
      insecure: true
    ingressRoute:
      dashboard:
        enabled: false
    ports:
      web:
        port: 80
        nodePort: 30080
      websecure:
        port: 443
        nodePort: 30443
        tls:
          enabled: true
    providers:
      kubernetesCRD:
        enabled: true
      kubernetesIngress:
        enabled: true
    ingressClass:
      enabled: true
      isDefaultClass: true
