apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-cert-token
  namespace: cert-manager
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-vault
  target:
    name: cloudflare-cert-token
    creationPolicy: Owner
  data:
    - secretKey: cf-token
      remoteRef:
        key: cloudflare-cert-token/credential
