apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: botkube-discord-secret
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: SecretStore
  target:
    name: botkube-discord-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Discord Bot Token
        discord_bot_token: "{{ .discord_bot_token }}"
        # Discord Bot ID
        discord_bot_id: "{{ .discord_bot_id }}"
        # Discord Guild/Server ID
        discord_guild_id: "{{ .discord_guild_id }}"
        # Channel IDs for different alert types
        discord_critical_channel_id: "{{ .discord_critical_channel_id }}"
        discord_network_channel_id: "{{ .discord_network_channel_id }}"
        discord_general_channel_id: "{{ .discord_general_channel_id }}"
  data:
  - secretKey: discord_bot_token
    remoteRef:
      key: botkube-discord
      property: bot_token
  - secretKey: discord_bot_id
    remoteRef:
      key: botkube-discord
      property: bot_id
  - secretKey: discord_guild_id
    remoteRef:
      key: botkube-discord
      property: guild_id
  - secretKey: discord_critical_channel_id
    remoteRef:
      key: botkube-discord
      property: critical_channel_id
  - secretKey: discord_network_channel_id
    remoteRef:
      key: botkube-discord
      property: network_channel_id
  - secretKey: discord_general_channel_id
    remoteRef:
      key: botkube-discord
      property: general_channel_id
