apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: botkube
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: botkube
      version: "v1.7.0"
      sourceRef:
        kind: HelmRepository
        name: botkube
        namespace: flux-system
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Environment variables for Discord integration
    env:
      - name: DISCORD_BOT_TOKEN
        valueFrom:
          secretKeyRef:
            name: botkube-discord-secret
            key: bot_token
      - name: DISCORD_BOT_ID
        valueFrom:
          secretKeyRef:
            name: botkube-discord-secret
            key: bot_id
      - name: DISCORD_GUILD_ID
        valueFrom:
          secretKeyRef:
            name: botkube-discord-secret
            key: guild_id

    # Communication settings - simplified for testing
    communications:
      default-group:
        discord:
          enabled: true
          channels:
            # Single test channel
            critical:
              name: k8s-critical
              bindings:
                sources:
                  - k8s-events
              notification:
                disabled: false
          token: "{{ .Env.DISCORD_BOT_TOKEN }}"
          botID: "{{ .Env.DISCORD_BOT_ID }}"
          server: "{{ .Env.DISCORD_GUILD_ID }}"

    # Simplified source configuration
    sources:
      k8s-events:
        displayName: "Kubernetes Events"
        kubernetes:
          enabled: true
          namespaces:
            include:
              - "longhorn-system"
              - "authentik"
              - "database"
          events:
            - type: error
            - type: warning
          resources:
            - type: v1/pods
              events:
                - create
                - delete
                - error

    # Simplified executor configuration for testing
    executors:
      kubectl-read-only:
        displayName: "Kubectl Read Only"
        kubectl:
          enabled: true
          namespaces:
            include:
              - "longhorn-system"
              - "authentik"
              - "database"
          commands:
            verbs: ["get", "describe", "logs"]
            resources: ["pods", "deployments", "services"]

    # Analytics and settings
    analytics:
      disable: true

    settings:
      clusterName: "kjho.me"
      upgradeNotifier: false
      log:
        level: info
        format: json

    # Resource settings
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi

    # Security context
    securityContext:
      runAsUser: 101
      runAsGroup: 101
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL

    # Service account with minimal required permissions
    serviceAccount:
      create: true
