apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: botkube
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: botkube
      version: "v1.7.0"
      sourceRef:
        kind: HelmRepository
        name: botkube
        namespace: flux-system
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Environment variables for Discord
    env:
      - name: DISCORD_BOT_TOKEN
        valueFrom:
          secretKeyRef:
            name: botkube-discord-secret
            key: bot_token
      - name: DISCORD_BOT_ID
        valueFrom:
          secretKeyRef:
            name: botkube-discord-secret
            key: bot_id
      - name: DISCORD_GUILD_ID
        valueFrom:
          secretKeyRef:
            name: botkube-discord-secret
            key: guild_id

    # Basic Discord communication
    communications:
      default-group:
        discord:
          enabled: true
          token: "{{ .Env.DISCORD_BOT_TOKEN }}"
          botID: "{{ .Env.DISCORD_BOT_ID }}"
          server: "{{ .Env.DISCORD_GUILD_ID }}"

    # Analytics and settings
    analytics:
      disable: true

    settings:
      clusterName: "kjho.me"
      upgradeNotifier: false
      log:
        level: info
        format: json

    # Resource settings
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi

    # Security context
    securityContext:
      runAsUser: 101
      runAsGroup: 101
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL

    # Service account with minimal required permissions
    serviceAccount:
      create: true
      annotations: {}

    # Add node selector for better scheduling
    nodeSelector: {}
    tolerations: []
    affinity: {}
