apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 10m
  chart:
    spec:
      chart: openebs
      version: 4.1.1
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: openebs
  values:
    # Disable unnecessary components that are causing image pull issues
    mayastor:
      enabled: false
    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: false
      replicated:
        mayastor:
          enabled: false

    # Disable observability stack (causing Docker Hub rate limit issues)
    loki-stack:
      enabled: false
    obs:
      callhome:
        enabled: false

    # Only enable local path provisioner
    localprovisioner:
      enabled: true
      basePath: /mnt/data1
      nodeSelector:
        kubernetes.io/hostname: nucx
      hostpathClass:
        name: openebs-hostpath
        isDefaultClass: true
        reclaimPolicy: Delete

    # Disable other components
    ndm:
      enabled: false
    ndmOperator:
      enabled: false
    admissionServer:
      enabled: false
