apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 10m
  chart:
    spec:
      chart: openebs
      version: 4.1.1
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: openebs
  values:
    localprovisioner:
      basePath: /mnt/data1
      nodeSelector:
        kubernetes.io/hostname: nucx
      hostpathClass:
        name: openebs-hostpath
        isDefaultClass: true
