---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik
      version: 2025.4.1
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  values:
    server:
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - auth.kjho.me
        tls:
          - secretName: authentik-tls
            hosts:
              - auth.kjho.me
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-cloudflare"
    authentik:
      redis:
        host: redis-master.redis.svc.cluster.local
        port: 6379
      postgresql:
        host: postgresql.postgresql.svc.cluster.local
        port: 5432
        name: postgres
        user: postgres
    redis:
      enabled: false
    postgresql:
      enabled: false
  valuesFrom:
    - kind: Secret
      name: authentik-secrets
      valuesKey: secret_key
      targetPath: authentik.secret_key
    - kind: Secret
      name: redis-secrets
      valuesKey: redis-password
      targetPath: authentik.redis.password
    - kind: Secret
      name: postgresql-secrets
      valuesKey: postgres-password
      targetPath: authentik.postgresql.password
