apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 10m
  ref:
    tag: v1.15.1
  url: https://github.com/cert-manager/cert-manager
