# /core/security/external-secrets/externalsecret-1password.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: discord-webhook-url
  namespace: external-secrets
spec:
  secretStoreRef:
    kind: SecretStore
    name: onepassword-sdk
  target:
    name: discord-webhook-url
    creationPolicy: Owner
  data:
    - secretKey: url
      remoteRef:
        key: "op://kjho.me/discord-webhook/add more/url"
