apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: onepassword-connect-token-staging
  namespace: external-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-vault
  target:
    name: onepassword-connect-token-staging
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: kjhome-provider-1p-sa/credential
