# helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 10m
  chart:
    spec:
      chart: external-secrets
      version: "0.18.1"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: external-secrets
  install:
    createNamespace: true
  values:
    installCRDs: true
