# /core/security/external-secrets/secretstore-1password.yaml
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: onepassword-sdk
  namespace: external-secrets
spec:
  provider:
    onepasswordSDK:
      vault: kjho.me
      auth:
        serviceAccountSecretRef:
          name: onepassword-connect-token-staging
          key: token
