# /core/security/external-secrets/secretstore-1password.yaml
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword-vault
spec:
  provider:
    onepasswordSDK:
      vault: kjho.me
      auth:
        serviceAccountSecretRef:
          name: onepassword-connect-token-staging
          namespaceRef:
            name: external-secrets
          key: token
