apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-secrets
  namespace: postgresql
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-vault
  target:
    name: postgresql-secrets
    creationPolicy: Owner
  data:
    - secretKey: postgres-password
      remoteRef:
        key: postgresql-secrets/postgres-password
    - secretKey: password
      remoteRef:
        key: postgresql-secrets/postgres-password
