apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: authelia
spec:
  interval: 5m
  chart:
    spec:
      chart: authelia
      version: "0.9.3"
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: flux-system
  values:
    domain: kjho.me

    ingress:
      enabled: true
      subdomain: auth
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: "cloudflare-issuer"
        traefik.ingress.kubernetes.io/router.tls: "true"
      rules:
        - host: "auth.kjho.me"
          http:
            paths:
              - path: "/"
                pathType: ImplementationSpecific
                backend:
                  service:
                    name: authelia
                    port:
                      number: 80
      tls:
        - hosts:
            - "auth.kjho.me"
          secretName: auth-kjho-me-tls

    pod:
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi

    configMap:
      authentication_backend:
        file:
          enabled: true
          path: /config/users_database.yml
          password:
            algorithm: argon2
            argon2:
              variant: argon2id
              iterations: 3
              memory: 65536
              parallelism: 4
              key_length: 32
              salt_length: 16

      session:
        name: authelia_session
        domain: kjho.me
        expiration: 1h
        inactivity: 5m
        remember_me: 1M
        cookies:
          - name: authelia_session
            domain: kjho.me
            authelia_url: https://auth.kjho.me
        redis:
          enabled: true
          host: redis-master.redis.svc.cluster.local
          port: 6379

      storage:
        local:
          enabled: true
          path: /config/db.sqlite3

      notifier:
        disable_startup_check: true
        filesystem:
          enabled: true
          filename: /config/notification.txt

      access_control:
        default_policy: deny
        rules:
          - domain: "*.kjho.me"
            policy: one_factor

    persistence:
      enabled: true
      storageClass: "openebs-hostpath"
      size: 1Gi
