apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: authelia
spec:
  interval: 5m
  chart:
    spec:
      chart: authelia
      version: "0.9.3"
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: flux-system
  values:
    domain: kjho.me

    ingress:
      enabled: true
      subdomain: auth
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: "cloudflare-issuer"
        traefik.ingress.kubernetes.io/router.tls: "true"
      tls:
        enabled: true
        secret: auth-kjho-me-tls

    pod:
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi

      env:
        - name: AUTHELIA_AUTHENTICATION_BACKEND_FILE_PASSWORD_KYLE
          valueFrom:
            secretKeyRef:
              name: authelia-admin-user
              key: password

    configMap:
      session:
        redis:
          enabled: true
          host: redis-master.redis.svc.cluster.local
          port: 6379

      access_control:
        default_policy: deny
        rules:
          - domain: "*.kjho.me"
            policy: one_factor

    persistence:
      enabled: true
      storageClass: "openebs-hostpath"
      size: 1Gi
