apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 10m
  timeout: 10m
  install:
    timeout: 10m
    remediation:
      retries: 3
  upgrade:
    timeout: 10m
    remediation:
      retries: 3
      remediateLastFailure: true
  chart:
    spec:
      chart: external-dns
      version: "1.15.0"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns
  values:
    # Use Cloudflare as the DNS provider
    provider: cloudflare

    # Cloudflare configuration
    cloudflare:
      # Use secret for API token
      secretName: external-dns-cloudflare-secret

    # Domain filter - only manage records for this domain
    domainFilters:
      - kjho.me

    # Policy for managing DNS records
    policy: sync  # Can be 'sync' or 'upsert-only'

    # Registry for tracking ownership
    registry: txt
    txtOwnerId: "kjhome-external-dns"

    # Source types to watch
    sources:
      - ingress
      - service

    # Deployment settings
    replicaCount: 1

    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 128Mi
        cpu: 100m

    # Run frequently to keep DNS in sync
    interval: 1m

    # Log level
    logLevel: info

    # Annotations to add to created DNS records
    txtPrefix: "kjhome-"
