apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: core-storage
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/core/storage
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
  retryInterval: 2m
  wait: true
