apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: core-authentik
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/core/authentik
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
  retryInterval: 2m
  wait: true
  dependsOn:
    - name: core-database
    - name: flux-system
